---

- name: Provisioning galuchat
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  vars_files:
    - vars/main.yml

  roles:
    - ubuntu-apt
    - create-www-data-user
    - nodejs
    - ubuntu-nodejs-nginx
    - ubuntu-postgresql
