---

- name: Ensure that nodejs directory is exist
  file: path={{nodejs_home}}/src state=directory mode=0755

- name: Download nodejs source code
  get_url: url={{nodejs_src_url}} dest={{nodejs_home}}/src/v{{nodejs_version}}.tar.gz

- name: Unpack nodejs
  unarchive: src={{nodejs_home}}/src/v{{nodejs_version}}.tar.gz dest={{nodejs_home}}/src copy=no creates={{nodejs_home}}/src/node-v{{nodejs_version}}

- name: Build nodejs
  shell: >
    cd {{nodejs_home}}/src/node-v{{nodejs_version}} && ./configure && make -j `nproc` && make install
