---

- name: Install dependencies
  apt: name=apt-transport-https

- name: Add APT key
  apt_key: url=https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280 validate_certs=False id=68576280

- name: Add APT repository
  apt_repository: repo="{{item}}" update_cache=yes
  with_items:
  - "deb https://deb.nodesource.com/node_6.x {{ansible_distribution_release}} main"
  - "deb-src https://deb.nodesource.com/node_6.x {{ansible_distribution_release}} main"

- name: Install nodejs
  apt: name=nodejs={{nodejs_version}}*

# Latest packages doesn't have 'node' executable anymore
# It were renamed to 'nodejs'. Add link to support old
# cookbooks which use the legacy 'node' command.
- stat: path=/usr/bin/node
  register: node_bin

- name: Add legacy node link
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  when: not node_bin.stat.exists
